conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=9',
    gap_x = 25,
    gap_y = 45,
    minimum_height = 5,
    minimum_width = 420,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    lua_load = '/home/franlegon/.config/conky/system_units.lua',
}

conky.text = [[
${color #0080FF}SYSTEM ${hr 2}${color}
Host:${alignR}$nodename
Uptime:${alignR}$uptime

${color #0080FF}CPU (Ryzen 7 PRO) ${hr 2}${color}
Total Usage:${alignR}${cpu}%
${color #0080FF}${cpubar 6}${color}
${cpugraph 30,420 0080FF 00FFFF}

${color #0080FF}MEMORY ${hr 2}${color}
RAM:${alignR}$mem / $memmax ($memperc%)
${color #A0A0A0}${alignr}${lua_parse get_mem_decimal}${color}
${color #0080FF}${membar 6}${color}
Swap:${alignR}$swap / $swapmax ($swapperc%)
${color #A0A0A0}${alignr}${lua_parse get_swap_decimal}${color}
${color #0080FF}${swapbar 6}${color}

${color #0080FF}STORAGE ${hr 2}${color}
Root (/):${alignR}${fs_used /} / ${fs_size /} (${fs_used_perc /}%)
${color #A0A0A0}${alignr}${lua_parse get_fs_decimal /}${color}
${color #0080FF}${fs_bar 6 /}${color}
Read:${alignR}${diskio_read}
${color #A0A0A0}${alignr}${lua_parse get_diskio_read_decimal}${color}
${diskiograph_read 25,420 0080FF 00FFFF}
Write:${alignR}${diskio_write}
${color #A0A0A0}${alignr}${lua_parse get_diskio_write_decimal}${color}
${diskiograph_write 25,420 0080FF 00FFFF}

${color #0080FF}NETWORK (wlp6s0) ${hr 2}${color}
IP Address:${alignR}${addr wlp6s0}
Down:${alignR}${downspeed wlp6s0} (${totaldown wlp6s0})
${color #A0A0A0}${alignr}${lua_parse get_downspeed_decimal wlp6s0} (${lua_parse get_totaldown_decimal wlp6s0})${color}
Max Down:${alignR}${lua get_max_down wlp6s0}
${color #A0A0A0}${alignr}${lua_parse get_max_down_decimal wlp6s0}${color}
${color #0080FF}${downspeedgraph wlp6s0 25,420 0080FF 00FFFF}${color}
Up:${alignR}${upspeed wlp6s0} (${totalup wlp6s0})
${color #A0A0A0}${alignr}${lua_parse get_upspeed_decimal wlp6s0} (${lua_parse get_totalup_decimal wlp6s0})${color}
Max Up:${alignR}${lua get_max_up wlp6s0}
${color #A0A0A0}${alignr}${lua_parse get_max_up_decimal wlp6s0}${color}
${color #0080FF}${upspeedgraph wlp6s0 25,420 0080FF 00FFFF}${color}

]]